on: push

jobs:
  spotify_to_jekyll:
    runs-on: ubuntu-latest
    name: Turn a Spotify playlist into a Jekyll post.
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create post
        uses: katydecorah/spotify-to-jekyll-action@v4.0
        env:
          SpotifyClientID: ${{ secrets.SpotifyClientID }}
          SpotifyClientSecret: ${{ secrets.SpotifyClientSecret}}
          SpotifyUser: ${{ secrets.SpotifyUser }}
          ImgDir: ${{ secrets.ImgDir }}
          UpdateDataFile: ${{ secrets.UpdateDataFile }}
          PostsDir: ${{ secrets.PostsDir }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "ðŸŽµ ${{ env.playlist }}"
          git push "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF}
